name: tt_19
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.4.3

dependencies:
  flutter:
    sdk: flutter
  calendar_date_picker2: ^1.1.7
  dropdown_button2: ^2.3.9
  provider: ^6.1.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  flutter_native_splash: ^2.4.3
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0
  intl: ^0.20.0
  collection: ^1.17.0
  smooth_page_indicator: ^1.2.0+3
  webview_flutter_wkwebview: ^3.16.2
  webview_flutter: ^4.10.0
  flutter_email_sender: ^6.0.3
  flutter_launcher_icons: ^0.14.1
  url_launcher: ^6.3.1
  get_it: ^8.0.2
  flagsmith: ^6.0.0
  in_app_review: ^2.0.10
  is_first_run: ^1.0.0
  get_ip_address: ^0.0.7
  http: ^1.2.2
  custom_progressbar: ^0.0.2
  shared_preferences: ^2.3.3

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.6 
  hive_generator: ^2.0.0

  
flutter_native_splash:
  color: "#6486CC" 
  image: assets/images/icon.png 
  
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"

flutter:

  uses-material-design: true


  assets:
  - assets/images/
  - assets/icons/